trigger:
- none

pool:
  vmImage: windows-latest

stages:
  - stage: checkoutcode
    jobs:
      - job: 'Checkoutcode'
        steps:
          - checkout: self

  - stage: MavenBuild
    jobs:
      - job: 'MavenBuild'
        steps:
        
        - task: Maven@4
          inputs:
           mavenPomFile: 'pom.xml'
           goals: 'install'
           publishJUnitResults: true
           testResultsFiles: '**/surefire-reports/TEST-*.xml'
           javaHomeOption: 'JDKVersion'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: false
           effectivePomSkip: false
           sonarQubeRunAnalysis: false