trigger:
- none

pool:
  name: My-Agent

stages:
  - stage: checkoutcode
    jobs:
      - job: 'Checkoutcode'
        steps:
          - checkout: self

  - stage: MavenBuild
    jobs:
      - job: 'MavenBuild'
        steps: 
        - task: Maven@4
          inputs:
           mavenPomFile: 'pom.xml'
           goals: 'install'
           publishJUnitResults: true
           testResultsFiles: '**/surefire-reports/TEST-*.xml'
           javaHomeOption: 'JDKVersion'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: false
           effectivePomSkip: false
           sonarQubeRunAnalysis: false

        - task: CopyFiles@2
          inputs:
           SourceFolder: '$(system.defaultworkingdirectory)'
           Contents: '**/*.jar'
           TargetFolder: '$(build.artifactstagingdirectory)'
           
        - task: PublishBuildArtifacts@1
          inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'artifact_yaml'
           publishLocation: 'Container'
           
 